# Generated by scripts/build_stubs.py -- do not edit.
# Relocated from _core/__init__.pyi to match the runtime submodule layout.
# ruff: noqa: E501, F401, F403, F405
import builtins
import typing
from yamc._core import (
    DoseCoefficients,
    Material,
    NeutronSource,
    PhotonCoefficients,
)

__all__ = [
    "get_radionuclides_from_chain",
]

def get_radionuclides_from_chain(nuclide_names: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]:
    r"""
    Find unstable activation products from a list of nuclide names.
    
    Args:
        nuclide_names (list[str]): Nuclide names present in the model materials.
    
    The transmutation network is assembled from the configured per-subsection
    sources (``yamc.transmutation_decay_data`` etc.).
    
    Returns:
        list[str]: Sorted list of unique radionuclide names.
    """
