# Generated by scripts/build_stubs.py -- do not edit.
# Relocated from _core/__init__.pyi to match the runtime submodule layout.
# ruff: noqa: E501, F401, F403, F405
import builtins
import typing
from yamc._core import (
    DoseCoefficients,
    Material,
    NeutronSource,
    PhotonCoefficients,
)

__all__ = [
    "has_mpi",
    "gpu_available",
    "list_gpu_adapters",
    "mpi_rank",
    "mpi_size",
    "mpi_finalize",
]

def has_mpi() -> builtins.bool:
    r"""
    Return ``True`` if yamc was built with MPI support.
    """

def gpu_available() -> builtins.bool:
    r"""
    Return ``True`` if the GPU compute path is usable -- yamc was built with the
    ``gpu`` feature and an f64-capable Vulkan adapter is present.
    """

def list_gpu_adapters() -> builtins.list[builtins.str]:
    r"""
    List the names of the f64-capable Vulkan GPU adapters on this host.
    
    Pass one of these names directly as ``compute=<name>`` to
    :meth:`Model.simulate_transport` to run on that specific adapter; plain
    ``compute='gpu'`` auto-selects (preferring a discrete GPU). Returns an
    empty list when there's no usable GPU (or yamc was built without the
    ``gpu`` feature). Pure enumeration -- it does not initialize the GPU.
    """

def mpi_rank() -> builtins.int:
    r"""
    Return this process's MPI rank (``0`` when not running under MPI).
    """

def mpi_size() -> builtins.int:
    r"""
    Return the number of MPI ranks (``1`` when not running under MPI).
    """

def mpi_finalize() -> None:
    r"""
    Finalize MPI. Call once before process exit in MPI runs; a no-op otherwise.
    """
