# Generated by scripts/build_stubs.py -- do not edit.
# Relocated from _core/__init__.pyi to match the runtime submodule layout.
# ruff: noqa: E501, F401, F403, F405
import builtins
import typing
from yamc._core import (
    DoseCoefficients,
    Material,
    NeutronSource,
    PhotonCoefficients,
)

__all__ = [
    "Discrete",
    "Histogram",
    "Uniform",
    "Normal",
    "Isotropic",
    "Monodirectional",
    "CylindricalRing",
    "fusion_neutron_spectrum",
    "tokamak_source",
    "tokamak_ion_density",
    "tokamak_ion_temperature",
    "tokamak_convert_a_alpha_to_r_z",
    "tokamak_neutron_source_density",
]

@typing.final
class Discrete:
    r"""
    Discrete energy distribution with specific energies and their probabilities.
    """
    @property
    def energies(self) -> builtins.list[builtins.float]:
        r"""
        Get the energy values.
        
        Returns:
            List[float]: Energy values in eV.
        """
    @property
    def probabilities(self) -> builtins.list[builtins.float]:
        r"""
        Get the probability values.
        
        Returns:
            List[float]: Probability for each energy.
        """
    def __new__(cls, energies: typing.Sequence[builtins.float], probabilities: typing.Sequence[builtins.float]) -> Discrete:
        r"""
        Create a discrete energy distribution.
        
        Args:
            energies: List of energy values in eV.
            probabilities: Relative probability for each energy. Normalized
                internally, so only the relative values matter.
        
        Returns:
            Discrete: A discrete energy distribution.
        
        Raises:
            ValueError: If energies and probabilities have different lengths, if
                        any probability is negative, or if all are zero.
        
        Examples:
            >>> import yamc
            >>> # 14.06 MeV neutrons (D-T fusion)
            >>> energy_dist = yamc.Discrete([14.06e6], [1.0])
        """
    def sample(self) -> builtins.float:
        r"""
        Sample an energy value from the distribution.
        
        Returns:
            float: Sampled energy in eV.
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display: the (energy, probability) points as a table.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Histogram:
    r"""
    Histogram (piecewise-constant) energy distribution over energy bins.
    """
    @property
    def boundaries(self) -> builtins.list[builtins.float]:
        r"""
        Get the bin boundaries.
        
        Returns:
            List[float]: Energy bin edges in eV, length ``n + 1``.
        """
    @property
    def probabilities(self) -> builtins.list[builtins.float]:
        r"""
        Get the per-bin probabilities, as supplied.
        
        Returns:
            List[float]: Relative probability mass for each bin.
        """
    def __new__(cls, boundaries: typing.Any, probabilities: typing.Sequence[builtins.float]) -> Histogram:
        r"""
        Create a histogram (piecewise-constant) energy distribution.
        
        Each bin ``i`` spans ``boundaries[i]`` to ``boundaries[i + 1]`` and holds
        probability mass ``probabilities[i]``; an energy is sampled by choosing a
        bin in proportion to its mass and then drawing uniformly within it.
        
        Args:
            boundaries: Either explicit energy bin edges in eV (length ``n + 1``,
                strictly ascending) or the name of a built-in group structure
                (e.g. ``"CCFE-709"``, ``"VITAMIN-J-175"``), whose edges are used.
            probabilities: Relative probability mass for each of the ``n`` bins.
                Normalized internally, so only the relative values matter (a raw
                multigroup flux per group can be passed directly).
        
        Returns:
            Histogram: A histogram energy distribution.
        
        Raises:
            ValueError: If a named group structure is unknown, if ``boundaries``
                is not exactly one longer than ``probabilities``, if the
                boundaries are not strictly ascending, if any probability is
                negative, or if all are zero.
        
        Examples:
            >>> import yamc
            >>> # 30% of source neutrons in [0, 1] MeV, 70% in [1, 20] MeV
            >>> energy_dist = yamc.sources.Histogram([0.0, 1e6, 20e6], [0.3, 0.7])
            >>> # or from a named group structure (709 per-group weights)
            >>> energy_dist = yamc.sources.Histogram("CCFE-709", flux_709)
        """
    def sample(self) -> builtins.float:
        r"""
        Sample an energy value from the distribution.
        
        Returns:
            float: Sampled energy in eV.
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display: the per-bin (range, probability) rows as a table.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Uniform:
    r"""
    Uniform energy distribution between two bounds.
    """
    @property
    def low(self) -> builtins.float:
        r"""
        Get the lower energy bound.
        
        Returns:
            float: Lower bound in eV.
        """
    @property
    def high(self) -> builtins.float:
        r"""
        Get the upper energy bound.
        
        Returns:
            float: Upper bound in eV.
        """
    def __new__(cls, low: builtins.float, high: builtins.float) -> Uniform:
        r"""
        Create a uniform energy distribution.
        
        Args:
            low: Lower energy bound in eV.
            high: Upper energy bound in eV.
        
        Returns:
            Uniform: A uniform energy distribution.
        
        Raises:
            ValueError: If low >= high (lower bound must be less than upper bound).
        
        Examples:
            >>> import yamc
            >>> # Uniform distribution from 1 MeV to 20 MeV
            >>> energy_dist = yamc.Uniform(1e6, 20e6)
        """
    def sample(self) -> builtins.float:
        r"""
        Sample an energy value from the distribution.
        
        Returns:
            float: Sampled energy in eV, uniformly distributed between low and high.
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display: the low / high bounds.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Normal:
    r"""
    Normal (Gaussian) energy distribution.
    """
    @property
    def mean(self) -> builtins.float:
        r"""
        Get the mean energy.
        
        Returns:
            float: Mean energy in eV.
        """
    @property
    def std_dev(self) -> builtins.float:
        r"""
        Get the standard deviation.
        
        Returns:
            float: Standard deviation in eV.
        """
    def __new__(cls, mean: builtins.float, std_dev: builtins.float) -> Normal:
        r"""
        Create a normal (Gaussian) energy distribution.
        
        Args:
            mean: Mean energy in eV.
            std_dev: Standard deviation in eV (must be positive).
        
        Returns:
            Normal: A normal energy distribution.
        
        Raises:
            ValueError: If std_dev is not positive.
        
        Examples:
            >>> import yamc
            >>> # Normal distribution centered at 14.06 MeV
            >>> energy_dist = yamc.Normal(14.06e6, 0.1e6)
        """
    def sample(self) -> builtins.float:
        r"""
        Sample an energy value from the distribution.
        
        Returns:
            float: Sampled energy in eV.
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display: the mean and standard deviation.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Isotropic:
    r"""
    Isotropic angular distribution (uniform over 4π steradians).
    """
    def __new__(cls) -> Isotropic:
        r"""
        Create an isotropic angular distribution.
        
        Returns:
            Isotropic: An isotropic angular distribution.
        
        Examples:
            >>> import yamc
            >>> angle_dist = yamc.Isotropic()
        """
    def sample(self) -> builtins.list[builtins.float]:
        r"""
        Sample a direction vector from the distribution.
        
        Returns:
            List[float]: Unit direction vector [u, v, w].
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Monodirectional:
    r"""
    Monodirectional angular distribution (single fixed direction).
    """
    @property
    def direction(self) -> builtins.list[builtins.float]:
        r"""
        Get the direction vector.
        
        Returns:
            List[float]: Unit direction vector [u, v, w].
        """
    @direction.setter
    def direction(self, value: typing.Sequence[builtins.float]) -> None:
        r"""
        Set the direction vector.
        
        Args:
            direction: Direction vector [u, v, w]. Will be normalized automatically.
        """
    def __new__(cls, direction: typing.Sequence[builtins.float]) -> Monodirectional:
        r"""
        Create a monodirectional angular distribution.
        
        Args:
            direction: Direction vector [u, v, w]. Will be normalized automatically.
        
        Returns:
            Monodirectional: A monodirectional angular distribution.
        
        Examples:
            >>> import yamc
            >>> # Particles emitted in +z direction
            >>> angle_dist = yamc.Monodirectional([0.0, 0.0, 1.0])
        """
    def sample(self) -> builtins.list[builtins.float]:
        r"""
        Sample a direction vector from the distribution.
        
        Returns:
            List[float]: Unit direction vector [u, v, w] (always the reference direction).
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display: the direction vector.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CylindricalRing:
    r"""
    Cylindrical spatial distribution (ring, annulus, or full cylinder).
    
    Samples radius, phi, and z independently from univariate distributions
    in a cylindrical coordinate system centered at ``origin``.
    
    Positions are computed as:
      ``x = origin[0] + radius * cos(phi)``
      ``y = origin[1] + radius * sin(phi)``
      ``z = origin[2] + z``
    
    Args:
        radius: Distribution of radial coordinates (e.g., ``yamc.Discrete([300], [1])``
            for a thin ring, or ``yamc.Uniform(200, 400)`` for an annulus).
        phi: Distribution of azimuthal angle in radians (e.g.,
            ``yamc.Uniform(0, 2*math.pi)`` for full ring).
        z: Distribution of axial coordinates (e.g., ``yamc.Discrete([0], [1])``
            for the midplane).
        origin: Center of the cylindrical reference frame [x, y, z] in cm.
            Defaults to [0, 0, 0].
    
    Examples:
        >>> import yamc, math
        >>> # Ring source at radius=300 cm in the midplane
        >>> space = yamc.CylindricalRing(
        ...     radius=yamc.Discrete([300], [1]),
        ...     phi=yamc.Uniform(0, 2*math.pi),
        ...     z=yamc.Discrete([0], [1]),
        ... )
    """
    @property
    def origin(self) -> builtins.list[builtins.float]:
        r"""
        Center of the cylindrical reference frame, ``[x, y, z]`` in cm.
        """
    @property
    def radius(self) -> typing.Any:
        r"""
        Radial distribution.
        """
    @property
    def phi(self) -> typing.Any:
        r"""
        Azimuthal-angle distribution (radians).
        """
    @property
    def z(self) -> typing.Any:
        r"""
        Axial distribution.
        """
    def __new__(cls, *, radius: Discrete | Uniform | Normal, phi: Discrete | Uniform | Normal, z: Discrete | Uniform | Normal, origin: typing.Optional[typing.Sequence[builtins.float]] = None) -> CylindricalRing: ...
    def sample(self) -> builtins.list[builtins.float]:
        r"""
        Sample a position from the distribution.
        
        Returns:
            List[float]: Position vector [x, y, z] in cm.
        """
    def _repr_html_(self) -> builtins.str:
        r"""
        Rich Jupyter display: the radial / azimuthal / axial distributions
        and the cylinder origin.
        """
    def __repr__(self) -> builtins.str: ...

def fusion_neutron_spectrum(ion_temp: builtins.float, reactants: builtins.str = 'DT') -> Normal:
    r"""
    Return a Gaussian energy distribution for fusion neutron emission.
    
    Computes the mean energy and spectral width using relativistic
    interpolation formulas from Ballabio et al. (Nucl. Fusion 38, 1998).
    
    Args:
        ion_temp: Ion temperature of the plasma in eV.
        reactants: Fusion reactants, either 'DD' or 'DT' (default: 'DT').
    
    Returns:
        Normal: A Normal distribution with mean and standard deviation
                corresponding to the fusion neutron energy spectrum (in eV).
    
    Raises:
        ValueError: If ion_temp is outside [0, 100 keV] or reactants is invalid.
    
    Examples:
        >>> import yamc
        >>> # D-T fusion neutron spectrum at 20 keV ion temperature
        >>> energy_dist = yamc.fusion_neutron_spectrum(20000.0)
        >>> # D-D fusion neutron spectrum
        >>> energy_dist = yamc.fusion_neutron_spectrum(20000.0, reactants='DD')
    """

def tokamak_source(*, major_radius: builtins.float, minor_radius: builtins.float, elongation: builtins.float, triangularity: builtins.float, mode: builtins.str, ion_density_centre: builtins.float, ion_density_peaking_factor: builtins.float, ion_density_pedestal: builtins.float, ion_density_separatrix: builtins.float, ion_temperature_centre: builtins.float, ion_temperature_peaking_factor: builtins.float, ion_temperature_beta: builtins.float, ion_temperature_pedestal: builtins.float, ion_temperature_separatrix: builtins.float, pedestal_radius: builtins.float, shafranov_factor: builtins.float, start_angle: builtins.float = 0.0, rotation_angle: builtins.float = 6.283185307179586, mesh_resolution: tuple[builtins.int, builtins.int] = (100, 100), grid_density: builtins.int = 500, fuel: typing.Optional[typing.Mapping[builtins.str, builtins.float]] = None) -> builtins.list[NeutronSource]:
    r"""
    Build the neutron sources describing a parametric tokamak plasma.
    
    The plasma is discretised onto a cylindrical (R, phi, Z) mesh: every
    non-empty voxel becomes a ring source sampling uniformly across the voxel
    and across the toroidal sector, emitting isotropically with the Ballabio
    spectrum at that voxel's emission-weighted ion temperature. One source is
    returned per (voxel, reaction), so D-D and D-T neutrons keep their own
    spectra. Strengths are normalised to sum to 1; the absolute neutron rate
    is set by the simulation, not here.
    
    The profile models are from Fausser et al., 'Tokamak D-T neutron source
    models for different plasma physics confinement modes', Fus. Eng. Des. 87
    (2012) 787, and the arguments match the ``openmc-plasma-source`` package's
    ``tokamak_source`` so the two can be compared directly. Two physics
    differences to expect in such a comparison: T(t,2n)4He is not included,
    since yamc has no T-T neutron spectrum model, where
    ``openmc-plasma-source`` takes one from NeSST (for D-T fuel the T-T yield
    is a small fraction of the D-T yield); and the birth peaks sit a few tens
    of keV apart, because yamc's Ballabio spectrum takes the zero-temperature
    neutron energy from the reaction Q value rather than from Ballabio's
    tabulated 14.021 / 2.4495 MeV.
    
    Args:
        major_radius: Plasma major radius (cm).
        minor_radius: Plasma minor radius (cm).
        elongation: Plasma elongation (dimensionless).
        triangularity: Plasma triangularity (dimensionless).
        mode: Confinement mode, one of 'L', 'H' or 'A'.
        ion_density_centre: Ion density at the plasma centre (m^-3).
        ion_density_peaking_factor: Ion density peaking factor (dimensionless).
        ion_density_pedestal: Ion density at the pedestal (m^-3).
        ion_density_separatrix: Ion density at the separatrix (m^-3).
        ion_temperature_centre: Ion temperature at the plasma centre (eV).
        ion_temperature_peaking_factor: Ion temperature peaking factor
                (dimensionless, alpha_T in the reference).
        ion_temperature_beta: Ion temperature beta exponent (dimensionless,
                beta_T in the reference).
        ion_temperature_pedestal: Ion temperature at the pedestal (eV).
        ion_temperature_separatrix: Ion temperature at the separatrix (eV).
        pedestal_radius: Minor radius at the pedestal (cm).
        shafranov_factor: Shafranov factor (cm), the outward radial shift of
                the magnetic surfaces.
        start_angle: Toroidal angle at which the plasma starts, in radians.
                Defaults to 0.
        rotation_angle: Toroidal extent of the plasma, in radians. Negative
                extends the plasma the other way from ``start_angle``.
                Defaults to a full torus.
        mesh_resolution: Number of (R, Z) mesh bins as a two-value tuple.
                Defaults to (100, 100). The toroidal direction is not a
                parameter: the plasma is axisymmetric, so it carries no
                structure. Each non-empty voxel costs one source, so a coarser
                mesh is cheaper to sample.
        grid_density: Points per dimension of the internal (a, alpha) grid
                mapped onto the mesh. Defaults to 500.
        fuel: Fuel species as keys ('D', 'T') and atom fractions as values,
                which must sum to 1. Defaults to 50:50 D-T.
    
    Returns:
        list[NeutronSource]: One ring source per (mesh voxel, reaction).
    
    Raises:
        ValueError: If the plasma parameters are inconsistent (for example a
                minor radius larger than the major radius), the fuel is not
                D and/or T, or the plasma is too cold to make neutrons.
    
    Examples:
        >>> import yamc
        >>> sources = yamc.sources.tokamak_source(
        ...     major_radius=906.0,
        ...     minor_radius=292.258,
        ...     elongation=1.557,
        ...     triangularity=0.270,
        ...     mode="H",
        ...     ion_density_centre=1.09e20,
        ...     ion_density_peaking_factor=1,
        ...     ion_density_pedestal=1.09e20,
        ...     ion_density_separatrix=3e19,
        ...     ion_temperature_centre=45.9e3,
        ...     ion_temperature_peaking_factor=8.06,
        ...     ion_temperature_beta=6.0,
        ...     ion_temperature_pedestal=6.09e3,
        ...     ion_temperature_separatrix=0.1e3,
        ...     pedestal_radius=0.8 * 292.258,
        ...     shafranov_factor=0.44789,
        ... )
        >>> model = yamc.Model(geometry, sources, tallies)  # doctest: +SKIP
    """

def tokamak_ion_density(*, mode: builtins.str, ion_density_centre: builtins.float, ion_density_peaking_factor: builtins.float, ion_density_pedestal: builtins.float, minor_radius: builtins.float, pedestal_radius: builtins.float, ion_density_separatrix: builtins.float, r: typing.Any) -> typing.Any:
    r"""
    Ion density of a tokamak plasma at a given minor radius.
    
    The density depends only on the minor radius, so this is the profile the
    parametric source is built from. Pass a float or a sequence of floats for
    ``r``; the return keeps that shape.
    
    Args:
        mode: Confinement mode, one of 'L', 'H' or 'A'.
        ion_density_centre: Ion density at the plasma centre (m^-3).
        ion_density_peaking_factor: Ion density peaking factor (dimensionless).
        ion_density_pedestal: Ion density at the pedestal (m^-3).
        minor_radius: Plasma minor radius (cm).
        pedestal_radius: Minor radius at the pedestal (cm).
        ion_density_separatrix: Ion density at the separatrix (m^-3).
        r: Local minor radius (cm), from 0 to ``minor_radius``.
    
    Returns:
        Ion density in m^-3, as a float or a list of floats.
    
    Raises:
        ValueError: If ``mode`` is not 'L', 'H' or 'A', or ``r`` falls outside
                the plasma.
    """

def tokamak_ion_temperature(*, r: typing.Any, mode: builtins.str, pedestal_radius: builtins.float, ion_temperature_pedestal: builtins.float, ion_temperature_centre: builtins.float, ion_temperature_beta: builtins.float, ion_temperature_peaking_factor: builtins.float, ion_temperature_separatrix: builtins.float, minor_radius: builtins.float) -> typing.Any:
    r"""
    Ion temperature of a tokamak plasma at a given minor radius.
    
    The temperature depends only on the minor radius, so this is the profile
    that sets the neutron spectrum across the plasma. Pass a float or a
    sequence of floats for ``r``; the return keeps that shape.
    
    Unlike the ``openmc-plasma-source`` helper of the same name, which takes
    keV and returns eV, every temperature here is in eV.
    
    Args:
        r: Local minor radius (cm), from 0 to ``minor_radius``.
        mode: Confinement mode, one of 'L', 'H' or 'A'.
        pedestal_radius: Minor radius at the pedestal (cm).
        ion_temperature_pedestal: Ion temperature at the pedestal (eV).
        ion_temperature_centre: Ion temperature at the plasma centre (eV).
        ion_temperature_beta: Ion temperature beta exponent (dimensionless).
        ion_temperature_peaking_factor: Ion temperature peaking factor
                (dimensionless).
        ion_temperature_separatrix: Ion temperature at the separatrix (eV).
        minor_radius: Plasma minor radius (cm).
    
    Returns:
        Ion temperature in eV, as a float or a list of floats.
    
    Raises:
        ValueError: If ``mode`` is not 'L', 'H' or 'A', or ``r`` falls outside
                the plasma.
    """

def tokamak_convert_a_alpha_to_r_z(*, a: typing.Any, alpha: typing.Any, shafranov_factor: builtins.float, minor_radius: builtins.float, major_radius: builtins.float, triangularity: builtins.float, elongation: builtins.float) -> tuple[typing.Any, typing.Any]:
    r"""
    Convert plasma (a, alpha) coordinates to (R, Z) coordinates.
    
    ``a`` is the minor radius of a flux surface and ``alpha`` the poloidal
    angle; the mapping applies triangularity, elongation and the Shafranov
    shift. Either argument may be a float or a sequence of floats, and a
    scalar broadcasts against a sequence.
    
    Args:
        a: Minor radius of the flux surface (cm).
        alpha: Poloidal angle (radians).
        shafranov_factor: Shafranov factor (cm).
        minor_radius: Plasma minor radius (cm).
        major_radius: Plasma major radius (cm).
        triangularity: Plasma triangularity (dimensionless).
        elongation: Plasma elongation (dimensionless).
    
    Returns:
        An ``(R, Z)`` tuple in cm, each a float or a list of floats.
    """

def tokamak_neutron_source_density(*, ion_density: typing.Any, ion_temperature: typing.Any, reaction: builtins.str = 'DT') -> typing.Any:
    r"""
    Neutron source density of a fusing plasma.
    
    Uses the Bosch-Hale parameterisation of the Maxwellian-averaged
    reactivity (Nucl. Fusion 32 (1992) 611), which is fitted for ion
    temperatures from 0.2 keV to 100 keV. Either numeric argument may be a
    float or a sequence of floats, and a scalar broadcasts against a sequence.
    
    Args:
        ion_density: Density of reacting pairs (m^-6): ``n_D * n_T`` for D-T,
                ``0.5 * n_D**2`` for D-D.
        ion_temperature: Ion temperature (eV).
        reaction: The fusing pair, either 'DD' or 'DT'. 'DD' counts the
                neutron-producing D(d,n)3He branch only.
    
    Returns:
        Neutron source density in neutrons/s/m^3, as a float or a list of
        floats.
    
    Raises:
        ValueError: If ``reaction`` is not 'DD' or 'DT'.
    """
