# Generated by scripts/build_stubs.py -- do not edit.
# Relocated from _core/__init__.pyi to match the runtime submodule layout.
# ruff: noqa: E501, F401, F403, F405
import builtins
import typing
from yani._core import (
    DoseCoefficients,
    Material,
    NeutronSource,
    PhotonCoefficients,
)

__all__ = [
    "dose_coefficients",
    "mass_attenuation_coefficient",
    "mass_energy_absorption_coefficient",
    "natural_abundance",
    "element_nuclides",
    "element_names",
    "reaction_names",
    "clear_nuclide_cache",
    "split_nuclide",
    "atomic_symbol",
    "atomic_number",
]

def dose_coefficients(particle: builtins.str, geometry: builtins.str = 'AP', data_source: builtins.str = 'icrp116') -> DoseCoefficients:
    r"""
    Return effective dose conversion coefficients.
    
    Provides fluence-to-effective-dose conversion coefficients based on
    ICRP Publication 74 or 116.
    
    Args:
        particle (str): 'neutron' or 'photon'.
        geometry (str): Irradiation geometry. One of:
            'AP' (Anterior-Posterior), 'PA' (Posterior-Anterior),
            'LLAT' (Left Lateral), 'RLAT' (Right Lateral),
            'ROT' (Rotational), 'ISO' (Isotropic)
        data_source (str): 'icrp74' or 'icrp116' (default: 'icrp116')
    
    Returns:
        DoseCoefficients: an object with ``.energy`` (eV), ``.coefficients``
        (pSv cm2), ``.units``, and ``.as_energy_function()``.
    
    Examples:
        import yani
    
        # Get ICRP-116 AP geometry dose coefficients
        dc = yani.data.dose_coefficients('neutron', 'AP')
        dc.energy          # incident energies in eV
        dc.coefficients    # fluence-to-dose coefficients
        dc.units           # 'pSv cm2'
    
        # Fold them into a flux tally via the energy_function= argument
        dose_tally = yamc.Tally(scores=['flux'], energy_function=dc.as_energy_function())
    
        # Or let the tally fetch the same coefficients itself:
        dose_tally = yamc.Tally(scores=['flux'], dose_coefficients=('neutron', 'AP'))
    
    References:
        - ICRP Publication 74: https://doi.org/10.1016/S0146-6453(96)90010-X
        - ICRP Publication 116: https://doi.org/10.1016/j.icrp.2011.10.001
    """

def mass_attenuation_coefficient(element: typing.Any) -> PhotonCoefficients:
    r"""
    Return the photon mass attenuation coefficient mu/rho of an element.
    
    Total attenuation with coherent scattering, from the NIST XCOM database,
    tabulated from 1 keV to 20 MeV for Z = 1 to 100. Dividing a material's dose
    or fluence by ``sum(density_i * mu_over_rho_i(E))`` is what a self-shielding
    estimate like :meth:`Material.contact_dose` does with it.
    
    Args:
        element (str | int): Element symbol (``'Fe'``) or atomic number (``26``).
    
    Returns:
        PhotonCoefficients: mu/rho in cm²/g against energy in eV.
    
    Examples:
        import yani
    
        iron = yani.data.mass_attenuation_coefficient('Fe')
        iron.interpolate(1.0e6)     # 0.05995 cm2/g at 1 MeV
        iron.energy, iron.coefficients
    
    References:
        - NIST Standard Reference Database 8 (XCOM): <https://doi.org/10.18434/T48G6X>
    """

def mass_energy_absorption_coefficient(material: builtins.str = 'air') -> PhotonCoefficients:
    r"""
    Return the mass energy-absorption coefficient mu_en/rho of a material.
    
    The fraction of incident photon energy actually absorbed per unit mass, less
    what scattered photons carry away, from NIST SRD 126. This is the response an
    absorbed dose in air folds against, and it is a different quantity from the
    attenuation coefficient: attenuation counts photons removed from the beam,
    this counts energy deposited.
    
    Args:
        material (str): Currently only ``'air'`` (dry, near sea level), tabulated
            from 1 keV to 20 MeV.
    
    Returns:
        PhotonCoefficients: mu_en/rho in cm²/g against energy in eV.
    
    Examples:
        import yani
    
        air = yani.data.mass_energy_absorption_coefficient('air')
        air.interpolate(1.0e6)      # 0.02789 cm2/g at 1 MeV
    
    References:
        - NIST Standard Reference Database 126: <https://doi.org/10.18434/T4D01F>
    """

def natural_abundance() -> typing.Any:
    r"""
    Return a dict of natural isotopic abundances by nuclide name.
    
    Returns:
        dict[str, float]: e.g. ``{"Li6": 0.07589, "Li7": 0.92411, ...}``
    """

def element_nuclides() -> typing.Any:
    r"""
    Return a dict mapping element symbol to its naturally occurring nuclides.
    
    Each value is a sorted list of nuclide names for that element.
    
    Returns:
        dict[str, list[str]]: e.g. ``{"Fe": ["Fe54", "Fe56", "Fe57", "Fe58"], ...}``
    """

def element_names() -> typing.Any:
    r"""
    Return a dict mapping element symbol to full element name.
    
    Returns:
        dict[str, str]: e.g. ``{"Fe": "iron", "Li": "lithium", ...}``
    """

def reaction_names() -> typing.Any:
    r"""
    Return a dict mapping MT numbers (int) to ENDF reaction notation strings.
    e.g. {2: "(n,elastic)", 18: "(n,fission)", 102: "(n,gamma)", ...}
    
    Each MT's own name, not an inversion of `REACTION_MT`. Several names map to
    one MT (`"fission"` and `"(n,fission)"` are both MT 18), so inverting a
    HashMap picked whichever the iteration order reached last: the same build
    could return `{18: "fission"}` on one run and `{18: "(n,fission)"}` on the
    next.
    """

def clear_nuclide_cache() -> None:
    r"""
    Clear any internally cached nuclide data.
    
    This forces subsequent reads to re-parse JSON files.
    
    Returns:
        None
    """

def split_nuclide(name: builtins.str) -> tuple[builtins.str, builtins.int, builtins.int]:
    r"""
    Split a nuclide name into its element symbol, mass number and isomeric state.
    
    The one place downstream code should ask, because the obvious way of doing
    it by hand is wrong for exactly the entry that is easiest to forget:
    stripping the trailing digits off ``"Ta180_m1"`` leaves ``"Ta180_m"`` and a
    mass number of 1, and natural tantalum really does contain Ta180m, so a
    composition built from :func:`natural_abundance` will hand you that name.
    
    Args:
        name (str): A nuclide name, e.g. ``"Fe56"`` or ``"Ta180_m1"``.
    
    Returns:
        tuple[str, int, int]: Element symbol, mass number, and isomeric state
            (0 for a ground state, 1 for the first metastable, and so on).
    
    Raises:
        ValueError: If the name is not a nuclide name.
    
    Examples:
        >>> yani.data.split_nuclide("Fe56")
        ('Fe', 56, 0)
        >>> yani.data.split_nuclide("Ta180_m1")
        ('Ta', 180, 1)
    """

def atomic_symbol(z: builtins.int) -> builtins.str:
    r"""
    Return the chemical symbol of an atomic number.
    
    Bound so that a caller naming files or directories from ENDF data does not
    have to carry its own copy of the periodic table, or install a second
    nuclear-data package to borrow one.
    
    Args:
        z (int): Atomic number, 0 to 118.
    
    Returns:
        str: The chemical symbol, e.g. ``"Fe"``.
    
    Raises:
        ValueError: If there is no element with that atomic number.
    
    Examples:
        >>> yani.data.atomic_symbol(26)
        'Fe'
        >>> yani.data.atomic_symbol(0)
        'n'
    
    Note:
        Z = 0 is the neutron, ``"n"``, and is not an error. ENDF libraries
        really do ship a neutron material (JENDL is one), so a caller walking a
        sublibrary will meet it.
    """

def atomic_number(symbol: builtins.str) -> builtins.int:
    r"""
    Return the atomic number of a chemical symbol.
    
    The inverse of :func:`atomic_symbol`.
    
    Args:
        symbol (str): A chemical symbol, e.g. ``"Fe"``. Case sensitive, and the
            symbol only: ``"fe"`` and ``"iron"`` are both refused.
    
    Returns:
        int: The atomic number.
    
    Raises:
        ValueError: If the symbol names no element.
    
    Examples:
        >>> yani.data.atomic_number("Fe")
        26
    """
