# Generated by scripts/build_stubs.py -- do not edit.
# Relocated from _core/__init__.pyi to match the runtime submodule layout.
# ruff: noqa: E501, F401, F403, F405
import builtins
import typing
from yani._core import (
    DoseCoefficients,
    Material,
    NeutronSource,
    PhotonCoefficients,
)

__all__ = [
    "MaterialCollection",
    "NameIter",
    "collections",
    "pnnl",
]

@typing.final
class MaterialCollection:
    r"""
    A read-only, name-keyed table of published material compositions.
    
    Indexing returns an ordinary :class:`Material`, freshly built each time,
    so it can be renamed and mutated without affecting the collection or any
    other lookup of the same name.
    
    Examples:
        >>> import yani
        >>> steel = yani.materials.pnnl["Steel, Stainless 304"]
        >>> steel.name = "firstwall_material"
        >>> yani.materials.pnnl.search("concrete")[:2]
        ['Concrete, Barite (Type BA)', 'Concrete, Barytes-Limonite']
    """
    @property
    def citation(self) -> builtins.str:
        r"""
        Short citation for the source document, e.g. ``"PNNL-15870, Rev. 2"``.
        """
    @property
    def url(self) -> builtins.str:
        r"""
        URL of the source document.
        """
    def __getitem__(self, name: builtins.str) -> Material:
        r"""
        Build the named material.
        
        Args:
            name (str): The source document's name, verbatim.
        
        Returns:
            Material: A new material carrying the collection's composition,
            density and name.
        
        Raises:
            KeyError: If no entry has that name. The message suggests near
                matches.
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of materials in the collection.
        """
    def __contains__(self, name: builtins.str) -> builtins.bool:
        r"""
        Whether a name is in the collection (exact match).
        """
    def __iter__(self) -> NameIter:
        r"""
        Iterate over the material names, in source-document order.
        """
    def __repr__(self) -> builtins.str: ...
    def names(self) -> builtins.list[builtins.str]:
        r"""
        Every material name, in source-document order.
        
        Returns:
            list[str]: All names in the collection.
        """
    def search(self, query: builtins.str) -> builtins.list[builtins.str]:
        r"""
        Names containing ``query``, compared case-insensitively.
        
        Args:
            query (str): Substring to look for, e.g. ``"concrete"``.
        
        Returns:
            list[str]: Matching names, ready to pass straight back to ``[]``.
        """
    def material(self, key: builtins.str, *, name: typing.Optional[builtins.str] = None, density: typing.Optional[builtins.float] = None, temperature: typing.Optional[builtins.float] = None, volume: typing.Optional[builtins.float] = None, transmutable: builtins.bool = False, id: typing.Optional[builtins.int] = None) -> Material:
        r"""
        Build the named material, overriding fields the collection does not set.
        
        Equivalent to ``collection[key]`` followed by attribute assignment,
        except for ``density``, which :class:`Material` does not allow to be
        reassigned after construction. Use it for a material used at other
        than its reference density, e.g. a concrete at a different porosity.
        
        Args:
            key (str): The source document's name, verbatim.
            name (Optional[str]): Rename the material, e.g. to match a mesh
                geometry's material name.
            density (Optional[float]): Mass density in g/cm3, replacing the
                collection's reference density.
            temperature (Optional[float]): Temperature in Kelvin.
            volume (Optional[float]): Volume in cm³.
            transmutable (bool): Mark for depletion by
                ``Model.simulate_transmutation``.
            id (Optional[int]): Material ID.
        
        Returns:
            Material: The material with the overrides applied.
        """
    def entry(self, name: builtins.str) -> dict:
        r"""
        The source document's own record for a material, for citation.
        
        Args:
            name (str): The source document's name, verbatim.
        
        Returns:
            dict: ``name``, ``number`` (the entry number in the source
            document), ``density`` (g/cm3), ``formula`` (or None),
            ``composition`` (element symbol or nuclide name -> atom
            fraction), ``citation`` and ``url``.
        """

@typing.final
class NameIter:
    r"""
    Iterator over a collection's material names.
    """
    def __iter__(self) -> NameIter: ...
    def __next__(self) -> typing.Optional[builtins.str]: ...

def collections() -> builtins.list[builtins.str]:
    r"""
    Names of the available material collections.
    
    Returns:
        list[str]: Collection names, each an attribute of ``yani.materials``.
    """

pnnl: MaterialCollection
r"""The PNNL Compendium of Material Composition Data for Radiation
Transport Modeling (PNNL-15870, Rev. 2): 410 materials keyed by the
report's own names."""
