# Generated by scripts/build_stubs.py -- do not edit.
# Relocated from _core/__init__.pyi to match the runtime submodule layout.
# ruff: noqa: E501, F401, F403, F405
import builtins
import typing
from yani._core import (
    DoseCoefficients,
    Material,
    NeutronSource,
    PhotonCoefficients,
)

__all__ = [
    "SphereLump",
    "CubeLump",
    "FoilLump",
    "CylinderLump",
    "WireLump",
]

@typing.final
class SphereLump:
    r"""
    A sphere, sized by the material's volume.
    
    The extreme case: a sphere has the least surface for its volume, so it has
    the longest mean chord and shields more than any other shape of the same
    volume. Convenient, but an upper bound rather than a neutral choice.
    """
    def __new__(cls) -> SphereLump:
        r"""
        A sphere. Its radius follows from ``Material(volume=...)``.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CubeLump:
    r"""
    A cube, sized by the material's volume.
    """
    def __new__(cls) -> CubeLump:
        r"""
        A cube. Its side follows from ``Material(volume=...)``.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FoilLump:
    r"""
    A flat slab of a stated thickness.
    
    The chord is twice the thickness whatever the area, so a foil's shielding
    does not depend on the volume at all -- the volume is still what makes
    ``activity`` and ``decay_heat`` available, but it plays no part here.
    """
    @property
    def thickness(self) -> builtins.float: ...
    def __new__(cls, thickness: builtins.float) -> FoilLump:
        r"""
        Args:
        thickness (float): Foil thickness in cm.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CylinderLump:
    r"""
    A cylinder of a stated radius; its height follows from the volume.
    """
    @property
    def radius(self) -> builtins.float: ...
    def __new__(cls, radius: builtins.float) -> CylinderLump:
        r"""
        Args:
        radius (float): Cylinder radius in cm.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class WireLump:
    r"""
    A cylinder long enough that its ends do not matter. Chord ``2r``.
    """
    @property
    def radius(self) -> builtins.float: ...
    def __new__(cls, radius: builtins.float) -> WireLump:
        r"""
        Args:
        radius (float): Wire radius in cm.
        """
    def __repr__(self) -> builtins.str: ...
