//! Driver for the GPU kernel's exact CPU twin (`run_multi_cell_transport_cpu`).
//!
//! The twin takes the same ~120 flat buffers the cubecl launcher binds, so
//! calling it from a test is a long positional splat. Every test that wants to
//! compare the production CPU against what the GPU would do shares this one
//! copy rather than repeating the splat.
//!
//! The twin needs no GPU: it is pure CPU code pinned bit-equal to the kernel by
//! the `cpu_gpu_equivalence_*` tests in `yamc-gpu`. So a twin-vs-production-CPU
//! test runs in CI, where an on-hardware test cannot.
#![allow(dead_code)]

use yamc_gpu::common::tallies::TalliesPack;
use yamc_gpu::neutron::transport::{
    run_multi_cell_transport_cpu, CollisionRecord, FissionBankInputs, MultiCellResult, PendDrain,
    SurvivalBiasingInputs,
};

/// Run the twin over `inputs`, scoring into `pack`.
///
/// `max_steps` bounds the per-history step count; `capture_trace` turns on the
/// per-collision record the issue-#40 matched-stream harness diffs.
pub fn run_twin(
    inputs: &yamc::gpu::GpuTransportInputs,
    pack: &TalliesPack,
    max_steps: u32,
    free_gas_threshold: f64,
    capture_trace: bool,
    pend_drain: PendDrain,
) -> (MultiCellResult, Vec<Vec<CollisionRecord>>) {
    run_multi_cell_transport_cpu(
        &inputs.seeds,
        &inputs.energies,
        &inputs.positions,
        &inputs.directions,
        &inputs.cell_aabbs,
        &inputs.cell_to_material,
        &inputs.surface_types,
        &inputs.surface_params,
        &inputs.surface_boundaries,
        &inputs.region_program,
        &inputs.log_energy_grid,
        &inputs.coarse_log_energy_grid,
        &inputs.coarse_meta,
        &inputs.fine_log_energy_grid,
        &inputs.fine_meta,
        &inputs.xs_elastic_per_material,
        &inputs.xs_absorption_per_material,
        &inputs.xs_inelastic_per_material,
        &inputs.xs_fission_per_material,
        &inputs.nu_bar_per_material,
        &inputs.beta_delayed_per_material,
        &inputs.fission_a_per_material,
        &inputs.fission_b_per_material,
        &inputs.fission_eout_kind_per_material,
        &inputs.fission_eout_n_energies_per_material,
        &inputs.fission_eout_ae_offset,
        &inputs.fission_eout_energy_grid_per_material,
        &inputs.fission_eout_n_x_per_material,
        &inputs.fission_eout_x_offset,
        &inputs.fission_eout_x_per_material,
        &inputs.fission_eout_cdf_per_material,
        &inputs.fission_eout_p_per_material,
        &inputs.fission_eout_interp_per_material,
        &inputs.xs_inelastic_per_mt_sparse,
        &inputs.target_mass_per_material,
        &inputs.q_inelastic_per_mt,
        &inputs.yield_per_mt_sparse,
        &inputs.permt_meta,
        &inputs.angle_n_energies,
        &inputs.angle_ae_offset,
        &inputs.angle_energy_grid,
        &inputs.angle_n_mu,
        &inputs.angle_mu_offset,
        &inputs.angle_mu,
        &inputs.angle_cdf,
        &inputs.angle_pdf,
        &inputs.angle_interp,
        &inputs.eout_kind,
        &inputs.eout_n_energies,
        &inputs.eout_ae_offset,
        &inputs.eout_energy_grid,
        &inputs.eout_n_x,
        &inputs.eout_x_offset,
        &inputs.eout_x,
        &inputs.eout_cdf,
        &inputs.eout_histogram_interp,
        &inputs.eout_p,
        &inputs.eout_interp,
        &inputs.eout_n_discrete,
        &inputs.corr_n_energies,
        &inputs.corr_n_components,
        &inputs.corr_ae_offset,
        &inputs.corr_energy_grid,
        &inputs.corr_n_x,
        &inputs.corr_x_offset,
        &inputs.corr_x,
        &inputs.corr_cdf,
        &inputs.corr_p,
        &inputs.corr_interp,
        &inputs.corr_n_discrete,
        &inputs.corr_n_mu,
        &inputs.corr_mu_offset,
        &inputs.corr_mu,
        &inputs.corr_mu_cdf,
        &inputs.corr_mu_pdf,
        &inputs.corr_mu_interp,
        &inputs.scatter_in_cm_per_mt,
        &inputs.elastic_angle_n_energies,
        &inputs.elastic_angle_ae_offset,
        &inputs.elastic_angle_energy_grid,
        &inputs.elastic_angle_n_mu,
        &inputs.elastic_angle_mu_offset,
        &inputs.elastic_angle_mu,
        &inputs.elastic_angle_cdf,
        &inputs.elastic_angle_pdf,
        &inputs.elastic_angle_interp,
        &inputs.temperature_k_per_material,
        &inputs.km_n_energies,
        &inputs.km_ae_offset,
        &inputs.km_energy_grid,
        &inputs.km_interp,
        &inputs.km_n_discrete,
        &inputs.km_n_x,
        &inputs.km_x_offset,
        &inputs.km_x,
        &inputs.km_p,
        &inputs.km_c,
        &inputs.km_r,
        &inputs.km_a,
        &inputs.evap_n_energies,
        &inputs.evap_n_components,
        &inputs.evap_ae_offset,
        &inputs.evap_theta_offset,
        &inputs.evap_energy_grid,
        &inputs.evap_theta,
        &inputs.evap_u,
        &inputs.nbps_n_bodies,
        &inputs.nbps_total_mass,
        &inputs.maxwell_n_energies,
        &inputs.maxwell_ae_offset,
        &inputs.maxwell_energy_grid,
        &inputs.maxwell_theta,
        &inputs.maxwell_u,
        &inputs.watt_n_energies,
        &inputs.watt_ae_offset,
        &inputs.watt_energy_grid,
        &inputs.watt_a,
        &inputs.watt_b,
        &inputs.watt_u,
        &inputs.urr_meta,
        &inputs.urr_ae_offset,
        &inputs.urr_cdf_offset,
        &inputs.urr_energy_grid,
        &inputs.urr_cdf,
        &inputs.urr_xs,
        &inputs.urr_atom_density,
        pack,
        &[],
        &SurvivalBiasingInputs::off(),
        &inputs.nuclide_select,
        &FissionBankInputs::off(),
        max_steps,
        free_gas_threshold,
        capture_trace,
        pend_drain,
    )
}
